import { Component, OnInit, NgZone } from '@angular/core';
import { Plugins } from '@capacitor/core';
const { LocalNotifications } = Plugins;

@Component({
  selector: 'app-local-notifications',
  templateUrl: './local-notifications.page.html',
  styleUrls: ['./local-notifications.page.scss']
})
export class LocalNotificationsPage implements OnInit {
  message = '';
  triggered = false;
  scheduled = false;

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    // When the user taps on the notification
    LocalNotifications.addListener('localNotificationActionPerformed', notif => {
      this.ngZone.run(() => {
        this.triggered = true;
        this.scheduled = false;
      });
    });
  }

  async createNotification() {
    await LocalNotifications.schedule({
      notifications: [
        {
          id: 1, // Unique id
          title: this.message,
          body: 'This is a local notification generated by Capacitor',
          schedule: { at: new Date(new Date().getTime() + 10000) },
          sound: null
        }
      ]
    });
    this.scheduled = true;
    this.triggered = false;
  }

  async cancelNotification() {
    try {
      await LocalNotifications.cancel(await LocalNotifications.getPending());
    } finally {
      this.scheduled = false;
    }
  }
}
